### ISSUE TITLE
Unable to open directly to "Support" screen

### ISSUE THREAD

**Issue by jasongaare** [helpscout/beacon-android-sdk-sample#108] opened 2020-07-01 15:56 UTC
Thank you for taking the time to submit an issue with all the details shown below. Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

Beacon version: 
```
implementation "com.helpscout:beacon-core:2.1.0"
implementation "com.helpscout:beacon-ui:2.1.0"
```

Hello, I am trying to find on a way on Android to open the Beacon to this screen:

![Screen Shot 2020-07-01 at 10 38 14 AM](https://user-images.githubusercontent.com/15896334/86265263-2e4e0480-bb89-11ea-89cf-38352b4a8bad.png)

I can open directly to the "email contact form" or directly to the "chat" but that's too restrictive, as I have no way to know if chat is available at certain time, and I'd prefer the customer choose their route whenever possible.

Is there a way to open directly to this support screen? iOS has this option,
```
[HSBeacon navigate:@"/ask/message/" beaconSettings: beaconSettings];
```
which works as I'd expect **but I cannot seem to replicate on Android.**

**Comment by scottyab** [comment] 2020-07-01 18:34
Hey @jasongaare seems like we're missing a custom navigation option on Android to land on the Ask screen.  I'll create an internal task to track this. 

Interestingly `/ask/message/` should go directly to the contact message screen. I'll touch base with iOS folks to confirm the expected behaviour. 

If you are using the latest version 2.1.0 there's a few workarounds that might help you achieve this in the meantime. 

* Option 1 -  you can update your Beacon's focus mode to "Ask first" in Help Scout Beacon builder. Now when Beacon is opened it will default to the Ask Tab first. 
![Image 2020-07-01 at 7 15 22 pm](https://user-images.githubusercontent.com/404105/86277809-40eb2c80-bbcf-11ea-85c9-b64d6c6311f7.png)

* Option 2 - Similar to option 1 but using a local config overide you can change the Focus mode ([see the docs here](https://developer.helpscout.com/beacon-2/android/#settings-customization)). This might be useful if, for example you had two different ways to open the Beacon in your App. 

This would open with Ask first tab selected
```
fun openBeaconForContact() {
        val overrides = BeaconConfigOverrides(
            focusMode = FocusMode.ASK_FIRST
        )
        Beacon.setConfigOverrides(overrides)
        BeaconActivity.open(context = this)
    }
```

This would open with Instant Answers tab selected
```
  fun openBeacon() {
        val overrides = BeaconConfigOverrides(
            focusMode = FocusMode.NEUTRAL
        )
        Beacon.setConfigOverrides(overrides)
        BeaconActivity.open(context = this)
    }
```

* Option 3 - If you create a Beacon that's contact only (docs disabled) by default the Ask screen will be loaded. 

Let me know if any of those options suits, 
Thanks, 
Scott

**Comment by jasongaare** [comment] 2020-07-01 19:05
Scott, thanks for the prompt feedback - I think the option 2 might just work! I will give it a whirl and let you know

**Comment by scottyab** [comment] 2020-07-02 10:19
Created internal ticket [ANDSDK-505](https://helpscout.atlassian.net/browse/ANDSDK-505 ) to Add custom navigation option to land on the Ask screen

**Comment by aliripe** [comment] 2021-01-19 11:38
Hey @jasongaare, we've released version 2.3.2 of the SDK and it now includes the option to open the Beacon directly to the Ask screen. Let us know what you think!
See the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details.
I'm closing this now, feel free to open another ticket if you run into any other issue or have any other suggestion.

**Closed by aliripe** 2021-01-19 11:38 UTC
Labels: enhancement

**Comment by jasongaare** [comment] 2021-01-22 03:05
Awesome thank you! We ended up using a webview in our app instead of the native SDK because of this issue and a few others but if we ever switch back to using the native SDKs I'll look forward to this!

**Comment by scottyab** [comment] 2021-01-22 10:10
> We ended up using a webview in our app instead of the native SDK

Hey @jasongaare, I'm keen to dig in a bit more if you have a minute. In my experience using an embedded webview provides and less native experience on mobile. I'm keen to understand the choice to opt for the Beacon JS SDK? Especially since option 2 noted above using the local override `FocusMode.ASK_FIRST` seemed to provide what you were after? Maybe that didn't work or it was the other issues you mention? :thinking_face: 

Perhaps you're using React Native? and felt a JavaScript based SDK/Library was more aligned with the rest of your app? 

I guess just keen on any feedback you wish to share either here or via email help@helpscout.com FOA Scott.AB. Thanks
