### ISSUE TITLE
Duplicate class error on Beacon 2.2.0

### ISSUE THREAD

**Issue by amTheerat** [helpscout/beacon-android-sdk-sample#127] opened 2020-09-08 10:46 UTC
Hi Beacon team I got duplicate class error when I trying to implement Beacon SDK version 2.2.0 by Gradle. I hope you guys have solution for this. Thanks. :D 

* Beacon version: 2.2.0
* Android OS version: 9.0
* Device make/model: Samsung S9

**Steps to reproduce**
1. Implement Beacon SDK version 2.2.0 by Gradle
2. Sync project
3. Run (It' will got that error)

**Actual outcome**
Beacon did not run on my project

**Expected outcome**
Beacon should run on my project and working fine

**Screenshots or GIFs**
![Screen Shot 2563-09-08 at 17 43 58](https://user-images.githubusercontent.com/32013539/92466816-e25bb380-f1fa-11ea-9555-b02e55044b43.png)
![Screen Shot 2563-09-08 at 17 38 08](https://user-images.githubusercontent.com/32013539/92466372-33b77300-f1fa-11ea-9949-b15bff1aa04d.png)

**Comment by scottyab** [comment] 2020-09-08 11:19
Hey @amTheerat is this a fresh install of Beacon 2.2.0 or have you upgraded from a previous version? 

In 2.2.0 with removed `beacon-core` can you confirm you've removed all referenced to it and cleaned / rebuilt project, thanks.

**Comment by BinhTNT** [comment] 2020-09-08 11:48
Hello,

I got the same issue. I'm upgrading Beacon 2.2.0 from 2.1.2. I tried to run gradlew clean, delete app/build folder but it did not help.

**Comment by scottyab** [comment] 2020-09-08 12:22
The error could be flagging a duplicate dependency?. When you run `./gradle app:dependencies` do you see duplicates from Beacon and another dependency? 
 
Just for context we updated Beacon SDK from 2.1.2 to 2.2.0 in our Help Scout Android app and didn't see this issue. Also the sample project [here](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/sample-kotlin/build.gradle) works ok and both have `minifyEnabled true`. Are either of you able to compile the sample project? I wondering does it still compile with your current app's dependencies? 

💭 I don't know if it's a side issue but I don't understand why jetified-beacon-ui-2.2.0-runtime.jar is appearing?, the Beacon SDK uses AndroidX and didn't think it would be processed by jetifier 🤔

**Comment by amTheerat** [comment] 2020-09-10 04:04
> Hey @amTheerat is this a fresh install of Beacon 2.2.0 or have you upgraded from a previous version?
> 
> In 2.2.0 with removed `beacon-core` (technically we merged it into beacon-ui) can you confirm you've removed all referenced to it and cleaned / rebuilt project, thanks.

This is a fresh install. I just start from 2.2.0 not upgraded from old version.

**Comment by scottyab** [comment] 2020-09-11 10:44
Hey @amTheerat thanks for confirming that. I still feel this is due to a clash in dependencies and we can hopefully resolve with a gradle `resolutionStrategy`.  Can you send us your complete dependency list/block? here or via help@helpscout.com - or better still if you're able to fork this sample repository, add your dependencies to one of the sample projects and verify/recreate this issue? This way we'll have a sandboxed way to reproduce the error you are seeing and we can help track down the conflict and resolve. 
Thanks.

**Comment by scottyab** [comment] 2020-09-16 07:17
Hey @amTheerat or @BinhTNT Are you still seeing this Duplicate class issue with updated SDK 2.2.1? I'm not sure how we can progress this issue without your depenancy list as I cannot recreate the error to enable me to investigate a fix.

**Comment by BinhTNT** [comment] 2020-09-16 09:11
Hi @scottyab The error doesn't happen any more in my side with updated SDK 2.2.1. Thank a lot for your support!

**Comment by aliripe** [comment] 2020-09-17 07:10
Hi @BinhTNT, Alicia hopping in with Scott, that's great news! I'll close this then.

Do let us know if you run into any more issues.

**Closed by aliripe** 2020-09-17 07:10 UTC
Labels: help wanted
