### ISSUE TITLE
Feedback survery never dissapear

### ISSUE THREAD

**Issue by krobert** [helpscout/beacon-android-sdk-sample#176] opened 2021-09-09 14:39 UTC
Hey, we are using version 3.0.2, some of our devs noticed that the customer service page not working.
![image](https://user-images.githubusercontent.com/6197932/132706369-22f210d6-696d-480e-9cc9-e85ed779a829.png)
When i open the usual screen, this survey appears.

if i rate, nothing happens, still on the same page, if i tap the close (x) a forever loading spinner is visible only.
I cannot revert back to old versions because its conflicting with a lot of third party libraries and the app  wont compile.

**Comment by jotaemepereira** [comment] 2021-09-09 17:35
Hey @krobert thanks for the report. I wasn't able to reproduce the issue but I got a couple of questions that could help me understand the problem:

- Which focus mode are you using in your Beacon (Neutral, Ask first, or Self-service)?
- Are your devs running the app with the `Don't keep activities` developer option turned on?
- The forever loading spinner only appears after you rate and try to close? If you try to close the article without a rating, is still happening?

With these answers I can have a clearer picture, if we can't still reproduce it, as a next step, I can try using your Beacon, for this, I suggest emailing the `BeaconId` to help@helpscout.com FOA mobile team.

Thanks!

**Comment by krobert** [comment] 2021-09-10 09:55
Hey @jotaemepereira 

- Im not sure about the focus mode, where can i check that?
- I don't enable Don't keep activities developer option
- the spinner is there only after i close. The rating only makes the bottom rate dissapear.

Some additional info if it helps:

At app start i set it up:
`
val overrides = BeaconConfigOverrides( chatEnabled = true, messagingEnabled = true, color = "#2C2431" ) Beacon.setConfigOverrides(overrides) Beacon.Builder().withBeaconId(beaconId).let { if (BuildConfig.DEBUG) { it.withLogsEnabled(true) } else it }.build()
`

Clicking on the support button (the email and signature is never empty i checked, just some legacy code)

`fun goToHelpScoutPage(helpScoutSignature: String, fullName: String, email: String) { Beacon.addPreFilledForm(PreFilledForm(subject = "...")) Beacon.addAttributeWithKey("Version", AppUtil.getAppVersion(this)) Beacon.addAttributeWithKey("Model", AppUtil.getModel()) Beacon.identify(email, fullName) BeaconActivity.openInSecureMode(this, helpScoutSignature) overridePendingTransition(0, 0) }`

**Comment by jotaemepereira** [comment] 2021-09-10 13:33
@krobert I tried that setup but I still didn't have any luck reproducing the issue. Can you send an email to help@helpscout.com citing the mobile team with the following:

- The `BeaconId` for your Beacon that is having the issue
- An email and a signature of a testing user

Thanks!

**Comment by scottyab** [comment] 2021-09-13 09:46
Hey @krobert I had a couple of additional things to double check with you. 

1) Are these the steps to reproduce that you are following?

Steps to reproduce: 
* User opens article they have not previously rated. (if they had previously rated the Rating bar would be hidden)
* Rating bar is shown at the bottom of the article
* User taps either :) or :(
* The rating animation is shown (the emoji nods or shakes depending)

Expected
* Article is still shown but the rating bar is hidden 

Actual
* Article is still shown but the rating bar is hidden 


2) When rating an article (tapping :) or :( ) the Beacon SDK will send an HTTP PUT request to the Beacon API `{beaconId}/docs/articles/{articleId}/feedback/{deviceId}`  If the PUT fails the rating bar would continue to be shown. I see you have `withLogsEnabled(true)` Are you seeing any HTTP errors in the logs when the user is tapping the Article feedback?

**Comment by krobert** [comment] 2021-09-13 09:53
@jotaemepereira  i need to gather the email and signature to send the emaul, but basically its for any user. 
@scottyab 
1. exactly. second time, i see the same screen, but no rating. Same happens if i tap on the X.
2. i will write to you about this later, to verify if we receive any error

**Comment by krobert** [comment] 2021-09-13 13:02
@scottyab i receive no error everything seems fine, 200 ok, but then im stuck on that screen

**Comment by scottyab** [comment] 2021-09-13 13:09
thanks for checking that @krobert. As @jotaemepereira mentions if you can let us know the `BeaconId` `email` and `signature` of a testing user we can attempt to recreate the error you are seeing. 

Additionally please could you provide the following details which are missing from this issue (they are noted in the GitHub issue template) 

* Android OS version:
* Device make/model:
* Impacted user count:

Thanks!

**Comment by krobert** [comment] 2021-09-13 15:22
@jotaemepereira what kind of testing user do you need? it can be any user who receives this issue, or you want a public test user that you can use?

**Comment by krobert** [comment] 2021-09-14 08:18
@scottyab the id, email etc is still in progress, trying to find the right person to get permission for sending it.

Meanwhile i checked the iOS they are still using the older version of the sdk, its seems that this popup im seeing is the first article from the customer support page:
![image](https://user-images.githubusercontent.com/6197932/133221768-be04e1e7-1925-4d48-924b-9ad4d948f57d.png)
But like i said, im stuck here and unable to close it or go anywhere from here.

Additional details you request is not important, its effected every os i was checking with.
Android 9-10-11. Nokia 7.1, Pixel 30, P30 pro etc. 
The impacted user count is currently 0, but i must do this upgrade. 
Previous version was 2.1.2, but i needed androidX, koin and multiple upgrades So i upgraded to 3.0.2
I cant go back to older versions, because it won't compile. But this is not optimal that i have to wait for a library like beacon when i want to upgrade, if i can suggest, please start removing these blocking third party libraries.

**Comment by scottyab** [comment] 2021-09-14 10:44
>The id, email etc is still in progress, trying to find the right person to get permission for sending it

@krobert I totally understand you want to seek permission before sharing user details but can you share the Beacon Id and which company you work for with Help@helpscout.com so we can attempt to recreate this issue. As you can see below here's my attempt with 3.0.2 one of our test Beacons showing what we expect for each of the rating types. 

| positive | negative |
| ------ | ----- |
![Screen Recording 2021-09-14 at 11 21 09 am](https://user-images.githubusercontent.com/404105/133240964-3aeb50e9-1c50-4786-945a-4c386dee29bc.gif)|![Screen Recording 2021-09-14 at 11 26 59 am](https://user-images.githubusercontent.com/404105/133242379-0ed71681-74e6-4dbf-85a9-846e8a0fe317.gif)



Looking at your supplied code the `chatEnabled = true, messagingEnabled = true,` in the  `BeaconConfigOverrides` could be a potential issue? (although I cannot tell for sure until I can check your Beacon config once you supply the BeaconId.) I must apologise as the feature overrides aren't well named (i.e messagingEnabled, chatEnabled and docsEnabled). It's not possible to enable a feature that isn't enabled in your Beacon's config, these were added as a way to override and disable features. I.e disabling chat for non paid users. We tried to highlight this in the developer docs [here](https://developer.helpscout.com/beacon-2/android/#settings-customization) but as mentioned the naming could be improved. 


> but i needed androidX, koin and multiple upgrades So i upgraded to 3.0.2
> if i can suggest, please start removing these blocking third party libraries.


I'd like to fully understand the issues you are facing here with the SDK's dependencies. Please could you send us feedback to help@helpscout.com feel free to be technical/detailed as it'll be fellow Android developers reading.

**Comment by krobert** [comment] 2021-09-14 12:18
@scottyab i think i found the issue. This only happens if i open Beacon with a given article id. 
Also this is the first time i open beacon during the app lifecycle. 
The main screen is not loaded properly behind the article.
`BeaconActivity.open(activity, BeaconScreens.ARTICLE_SCREEN, arrayListOf(articleId))`

Can you try out with this approach?

**Comment by scottyab** [comment] 2021-09-14 12:42
> The main screen is not loaded properly behind the article.

Sorry if this isn't clear but this is the expected behaviour. We designed [open direct to article](https://developer.helpscout.com/beacon-2/mobile/customize/#open-to-an-article) to load an article but not the full Beacon. So I would expect the Beacon landing page not the be opened in the background. It would help if you let us know what you're trying to achieve/desired behavour as potentially there's another way of achieving this. I.e [Custom suggestions](https://developer.helpscout.com/beacon-2/mobile/customize/#custom-suggestions) 

I'm still unable to recreate the issue you are seeing. See the gif below which uses our internal Beacon sample where I can specific the `articleId` that's passed to `BeaconActivity.open(activity, BeaconScreens.ARTICLE_SCREEN, arrayListOf(articleId))`. 

![Screen Recording 2021-09-14 at 01 33 02 pm](https://user-images.githubusercontent.com/404105/133258410-98644e9b-69e9-4161-9ddf-88d2291dc0cb.gif)

I cannot assist further until you let us know the details requested in the previous message (Beacon Id and company) thanks

**Comment by krobert** [comment] 2021-09-14 20:43
@scottyab I want to achive the same as in the gif, but somehow the main sreen is opened in the background, which is not closed by presssing the X. I see you are using 3.1.0, but the current released version is 3.0.2. Can you try downgrading the sdk?  Maybe its fixed in the next release.

**Comment by scottyab** [comment] 2021-09-15 09:42
That is strange behaviour. I don't have a clear picture of all the code you are using apart from the snippets here. It would ideal if you could fork this repo and copy & paste your beacon calling/config code into the [Simple Koltin](https://github.com/helpscout/beacon-android-sdk-sample/tree/master/sample-kotlin) sample and share it will us, either privately via github or via help@helpscout.com  

Something that looks unusual in your gif apart from the weird blinking, I don't understand why you're loading an article from the Customer support menu?  it might be a business requirement? typically this type of menu would open the Beacon landing page. 

❓ Are you calling  `BeaconActivity.openInSecureMode(this, helpScoutSignature)`
Then immediately `BeaconActivity.open(activity, BeaconScreens.ARTICLE_SCREEN, arrayListOf(articleId))`  ?? if so this could be an issue as the SDK was not designed this way. As mentioned in the previous message it would help if you could give us more context on what you are trying to achieve.  

I'm really keen to help but without the Beacon Id or a clear reproducible demo it's difficult to know how to assist further. 

🗒️ Good spot on the version `3.1.0` but it's a red herring 🎣 and the code is the same as 3.0.2, it's just we have automatically incremented the version on our local `develop` branch.

**Comment by krobert** [comment] 2021-09-15 15:57
@scottyab please ignore that im opening an article from there. I put the id there to be able to show it to you.
I can't give you any more details (signature, id etc.) until i receive permission for it.  

So just to make it clear, i have these 2 methods 
1. open article
2. open customer service page

I will try with your sample code tomorrow, but i really posted every code we have for this beacon, every other code is just your sdk code. I don't have BeaconActivity in the manifest, im not doing any tricks, just calling these methods on the button click.

```
fun goToHelpScoutArticle(activity: Activity, articleId: String) {
        BeaconActivity.open(activity, BeaconScreens.ARTICLE_SCREEN, arrayListOf(articleId))
    }

    fun goToHelpScoutPage(
        activity: Activity,
        helpScoutSignature: String?,
        fullName: String?,
        email: String?
    ) {
        Beacon.addPreFilledForm(PreFilledForm(subject = "..."))
        Beacon.addAttributeWithKey("Version", AppUtil.getAppVersion(activity))
        Beacon.addAttributeWithKey("Model", AppUtil.getModel())
        if (!email.isNullOrEmpty()) {
            Beacon.identify(email, fullName)
            if (helpScoutSignature.isNullOrEmpty()) {
                BeaconActivity.open(activity)
            } else {
                BeaconActivity.openInSecureMode(activity, helpScoutSignature)
            }
            activity.overridePendingTransition(0, 0)
        } else {
            BeaconActivity.open(activity)
        }
    }
```

The last code part is the setUp during app launch, but its not related to this issue
```
suspend fun ConfigurationRepository.setUpBeacon() {
    val beaconId = getBeaconId()
    val overrides = BeaconConfigOverrides(
        chatEnabled = true, messagingEnabled = true, color = "#2C2431"
    )
    Beacon.setConfigOverrides(overrides)
    Beacon.Builder()
        .withBeaconId(beaconId).let {
            if (BuildConfig.DEBUG) {
                it.withLogsEnabled(true)
            } else it
        }.build()
}
```

**Comment by krobert** [comment] 2021-09-16 11:11
Another thing, here is the layout inspector, just to prove its a beacon layout that is visible.
![image](https://user-images.githubusercontent.com/6197932/133602094-c1d587ec-f5a0-41b0-9389-801371af71ef.png)

**Comment by jotaemepereira** [comment] 2021-09-16 18:59
Hey @krobert, I tried with the code you provided and I'm still not able to reproduce the issue. Were you able to reproduce it using our sample apps?

Is it possible for you to send us which company are you working for? It will not be necessary to send us the `BeaconId`.

**Comment by krobert** [comment] 2021-09-27 11:08
@jotaemepereira sorry for the late answer, its Oda or maybe its Kolonial in your database

**Comment by scottyab** [comment] 2021-09-27 16:16
Hi @krobert I've attempted to recreate using the "Chat Test" Beacon on your account but we are still unable to reproduce this issue 🤔 . I cannot see a way forward unless it's device/region related or the way the SDK is being used? Could you fork the simple kotlin project add your code and demonstrate via video that the issue is reproducible?    

Also side note I'm not clear why you're `BeaconConfigOverrides(chatEnabled = true, messagingEnabled = true ...` when all your Beacon's have all the settings enabled.

**Comment by jotaemepereira** [comment] 2021-11-29 20:56
Hey @krobert we didn't have more feedback for this issue so I'm going to close it for now. 

Feel free to re-open it providing some code in the sample-repo so we can have a better look at it. Thanks!

**Closed by jotaemepereira** 2021-11-29 20:56 UTC
