### ISSUE TITLE
ClassNotFoundException when calling BeaconActivity.open(..) with proguard-android-optimize

### ISSUE THREAD

**Issue by Ditscheridou** [helpscout/beacon-android-sdk-sample#153] opened 2021-01-15 15:41 UTC
Thank you for taking the time to submit an issue with the details requested below. Our engineering team actively monitors issues submitted to this repo and will generally respond within 2 business days.

**Please note the following:**

- **Please ensure you are testing on the latest version of the SDK ahead of submitting a report.**
- **All reports are required to include steps to reproduce any issues reported.** 
- **Issues logged without this information may be closed until more information is made available.**

**Technical details**

- Beacon version: 2.3.1
- Android OS version: 10 
- Device make/model: Xiaomi Mi 3
- Impacted user count: 0
- Kotlin version: 1.4.21

**Actual outcome**

When trying to open the BeaconActivity, the app crashes with following (maybe r8 related?) error: 
`  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/helpscout/beacon/internal/presentation/common/c;
        at com.helpscout.beacon.ui.BeaconActivity.open(Unknown Source:0)
        at com.vmaxpro.view.fragments.settings.SettingsFragment$createHelpCenterListItems$1.invoke(SettingsFragment.kt:86)
        at com.vmaxpro.view.fragments.settings.SettingsFragment$createHelpCenterListItems$1.invoke(SettingsFragment.kt:30)
        at com.vmaxpro.view.fragments.settings.ExternalResourceViewHolder$bind$1.invoke(SettingsViewHolder.kt:80)
        at com.vmaxpro.view.fragments.settings.ExternalResourceViewHolder$bind$1.invoke(SettingsViewHolder.kt:75)
        at com.vmaxpro.view.listeners.OnSingleClickListener$1.onClick(OnSingleClickListener.kt:18)
        at com.vmaxpro.view.listeners.OnSingleClickListener.onClick(OnSingleClickListener.kt:26)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27355)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.ClassNotFoundException: com.helpscout.beacon.internal.presentation.common.c
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.helpscout.beacon.ui.BeaconActivity.open(Unknown Source:0) 
        at com.vmaxpro.view.fragments.settings.SettingsFragment$createHelpCenterListItems$1.invoke(SettingsFragment.kt:86) 
        at com.vmaxpro.view.fragments.settings.SettingsFragment$createHelpCenterListItems$1.invoke(SettingsFragment.kt:30) 
        at com.vmaxpro.view.fragments.settings.ExternalResourceViewHolder$bind$1.invoke(SettingsViewHolder.kt:80) 
        at com.vmaxpro.view.fragments.settings.ExternalResourceViewHolder$bind$1.invoke(SettingsViewHolder.kt:75) 
        at com.vmaxpro.view.listeners.OnSingleClickListener$1.onClick(OnSingleClickListener.kt:18) 
        at com.vmaxpro.view.listeners.OnSingleClickListener.onClick(OnSingleClickListener.kt:26) 
        at android.view.View.performClick(View.java:7140) 
        at android.view.View.performClickInternal(View.java:7117) 
        at android.view.View.access$3500(View.java:801) 
        at android.view.View$PerformClick.run(View.java:27355) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7397) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/helpscout/beacon/a/d/a/a;
        at com.helpscout.beacon.ui.BeaconActivity.open(Unknown Source:0) 
        at com.vmaxpro.view.fragments.settings.SettingsFragment$createHelpCenterListItems$1.invoke(SettingsFragment.kt:86) 
        at com.vmaxpro.view.fragments.settings.SettingsFragment$createHelpCenterListItems$1.invoke(SettingsFragment.kt:30) 
        at com.vmaxpro.view.fragments.settings.ExternalResourceViewHolder$bind$1.invoke(SettingsViewHolder.kt:80) 
        at com.vmaxpro.view.fragments.settings.ExternalResourceViewHolder$bind$1.invoke(SettingsViewHolder.kt:75) 
        at com.vmaxpro.view.listeners.OnSingleClickListener$1.onClick(OnSingleClickListener.kt:18) 
        at com.vmaxpro.view.listeners.OnSingleClickListener.onClick(OnSingleClickListener.kt:26) 
        at android.view.View.performClick(View.java:7140) 
        at android.view.View.performClickInternal(View.java:7117) 
        at android.view.View.access$3500(View.java:801) 
        at android.view.View$PerformClick.run(View.java:27355) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7397) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
     Caused by: java.lang.ClassNotFoundException: com.helpscout.beacon.a.d.a.a
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.helpscout.beacon.ui.BeaconActivity.open(Unknown Source:0) 
        at com.vmaxpro.view.fragments.settings.SettingsFragment$createHelpCenterListItems$1.invoke(SettingsFragment.kt:86) 
        at com.vmaxpro.view.fragments.settings.SettingsFragment$createHelpCenterListItems$1.invoke(SettingsFragment.kt:30) 
        at com.vmaxpro.view.fragments.settings.ExternalResourceViewHolder$bind$1.invoke(SettingsViewHolder.kt:80) 
        at com.vmaxpro.view.fragments.settings.ExternalResourceViewHolder$bind$1.invoke(SettingsViewHolder.kt:75) 
        at com.vmaxpro.view.listeners.OnSingleClickListener$1.onClick(OnSingleClickListener.kt:18) 
        at com.vmaxpro.view.listeners.OnSingleClickListener.onClick(OnSingleClickListener.kt:26) 
        at android.view.View.performClick(View.java:7140) 
        at android.view.View.performClickInternal(View.java:7117) 
        at android.view.View.access$3500(View.java:801) 
        at android.view.View$PerformClick.run(View.java:27355) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7397) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/koin/core/KoinComponent;
        at com.helpscout.beacon.ui.BeaconActivity.open(Unknown Source:0) 
        at com.vmaxpro.view.fragments.settings.SettingsFragment$createHelpCenterListItems$1.invoke(SettingsFragment.kt:86) 
        at com.vmaxpro.view.fragments.settings.SettingsFragment$createHelpCenterListItems$1.invoke(SettingsFragment.kt:30) 
        at com.vmaxpro.view.fragments.settings.ExternalResourceViewHolder$bind$1.invoke(SettingsViewHolder.kt:80) 
        at com.vmaxpro.view.fragments.settings.ExternalResourceViewHolder$bind$1.invoke(SettingsViewHolder.kt:75) 
        at com.vmaxpro.view.listeners.OnSingleClickListener$1.onClick(OnSingleClickListener.kt:18) 
        at com.vmaxpro.view.listeners.OnSingleClickListener.onClick(OnSingleClickListener.kt:26) 
        at android.view.View.performClick(View.java:7140) 
        at android.view.View.performClickInternal(View.java:7117) 
        at android.view.View.access$3500(View.java:801) 
        at android.view.View$PerformClick.run(View.java:27355) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7397) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.koin.core.KoinComponent" on path: DexPathList[[zip file "/data/app/com.vmaxpro-qDETxeQSiEVhGI_wTYsDog==/base.apk"],nativeLibraryDirectories=[/data/app/com.vmaxpro-qDETxeQSiEVhGI_wTYsDog==/lib/arm64, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.helpscout.beacon.ui.BeaconActivity.open(Unknown Source:0) 
        at com.vmaxpro.view.fragments.settings.SettingsFragment$createHelpCenterListItems$1.invoke(SettingsFragment.kt:86) 
        at com.vmaxpro.view.fragments.settings.SettingsFragment$createHelpCenterListItems$1.invoke(SettingsFragment.kt:30) 
        at com.vmaxpro.view.fragments.settings.ExternalResourceViewHolder$bind$1.invoke(SettingsViewHolder.kt:80) 
        at com.vmaxpro.view.fragments.settings.ExternalResourceViewHolder$bind$1.invoke(SettingsViewHolder.kt:75) 
        at com.vmaxpro.view.listeners.OnSingleClickListener$1.onClick(OnSingleClickListener.kt:18) 
        at com.vmaxpro.view.listeners.OnSingleClickListener.onClick(OnSingleClickListener.kt:26) 
        at android.view.View.performClick(View.java:7140) 
        at android.view.View.performClickInternal(View.java:7117) 
        at android.view.View.access$3500(View.java:801) 
        at android.view.View$PerformClick.run(View.java:27355) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7397) 
        at java.lang.reflect.Method.invoke(Native Method)`

**Expected outcome**

  The BeaconActivity should open normally

**Steps to reproduce**

Im currently not sure how to reproduce this error. I just wanted to ask if this error is known and what i can do to resolve it.

**Comment by jotaemepereira** [comment] 2021-01-15 18:39
Hey @Ditscheridou! Are you using any ProGuard optimization settings? In that case, do you mind to share it with us? This is probably by a bug in our side that it should be fixed in the next release (2.3.2), but let us investigate just in case.

**Comment by Ditscheridou** [comment] 2021-01-18 09:27
Hi! 

Yeah i am using proguard, but i keep the package for helpscout like this: 

`-keep class retrofit2.** { *; }
-keep class okio.** { *; }
-dontwarn retrofit2.**
-dontwarn okio.**
-keep class com.helpscout.** {*;}
-dontwarn com.helpscout.**
-keep class com.elyeproj.wikisearchcount.Model** { *; }

-keepclassmembers class fqcn.of.javascript.interface.for.webview {
   public *;
}

-keepattributes InnerClasses

-keep class io.jsonwebtoken.** { *; }
-keepnames class io.jsonwebtoken.* { *; }
-keepnames interface io.jsonwebtoken.* { *; }

-keep class org.bouncycastle.** { *; }
-keepnames class org.bouncycastle.** { *; }
-dontwarn org.bouncycastle.**`

**Comment by scottyab** [comment] 2021-01-18 09:39
Hey @Ditscheridou 

You should not need to define any additional ProGuard configuration for Helpscout's Beacon SDK as we supply this as part of the AAR file in the proguard.txt. So `-keep class com.helpscout.** {*;}` and `-dontwarn com.helpscout.**` should not be needed. Please see our [Sample app](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/sample-kotlin/build.gradle#L38) in this repository uses ProGuard with just the default proguard rules.

@jotaemepereira was asking specifically about whether your app is using the **optimized** ProGuard settings? i.e ` proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')`. There's an existing issue for this #125 which we have recently fixed and will be included in the next version of the SDK. 

Are you using the 'proguard-android-optimize.txt'?

**Comment by Ditscheridou** [comment] 2021-01-18 09:51
oh yes sorry. I am using this `getDefaultProguardFile('proguard-android-optimize.txt')` file,yes. So i will use this without optimize for the moment

**Comment by scottyab** [comment] 2021-01-18 10:06
Thanks for confirming and applying a workaround for now. We'll update you when we release the next SDK version. 

Also just to note you can subscribe to release updates here from this Github repository.  
![Image 2021-01-18 at 10 04 30 am](https://user-images.githubusercontent.com/404105/104900954-a7217c00-5974-11eb-8c2b-752191051fed.png)

**Comment by jotaemepereira** [comment] 2021-01-18 17:29
👋 Hey @Ditscheridou I'm going ahead and close this because we were able to confirm that it is a duplicate of #125. We will update #125 once the fix is released. Thanks!

**Closed by jotaemepereira** 2021-01-18 17:29 UTC
Labels: duplicate
