### ISSUE TITLE
Is there a way for the app to know when a message just sent?

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-android-sdk-sample#126] opened 2020-09-03 15:43 UTC
Hello,

When the app send a message from contact form, is it supported for the app to trigger a such event?

Thanks,
Binh

**Comment by shaunmcilroy** [comment] 2020-09-03 16:15
Hey @BinhTNT -- I'm unsure what the ask is here in terms of functionality. Would you be able to clarify what your anticipated use case would be for such an event and we'll be able to see if there's anything we can suggest?

**Comment by BinhTNT** [comment] 2020-09-03 16:25
Hi @shaunmcilroy Sorry for not clarify, I asked about the callback event like lifecycle events, that will be called after every time a message sent. I'm wondering if it's supported such an event. For more detail of my use case is that when a user being contact form, I want to know if that user just dismiss contact form or process sending a the message. Is there a chance for me to achieve this checking on user behavior?
Thanks,
Binh

**Comment by codenameDuchess** [comment] 2020-09-06 12:42
Hi @BinhTNT, thanks for providing these additional details about your use case. We understand how being able to intercede when a user dismisses the contact form without sending a message would be helpful, but unfortunately we do not have a way for you to hook into and listen for such an event at this time. 

We will, however, open a ticket to discuss this with our product team and determine if it is an enhancement we may be able to add in the future. We'll let you know once we have a decision there.  Thanks for reaching out with the request.

[Internal tracking link](https://helpscout.atlassian.net/browse/MOBILE-393).

**Comment by BinhTNT** [comment] 2020-09-07 03:56
Hi @codenameDuchess Thank you for your information!

**Comment by scottyab** [comment] 2020-09-09 08:34
Also for extra context, this is a similar request to issue #81

**Comment by scottyab** [comment] 2022-01-18 14:44
Apologies for the late actioning of this, but we should have closed this issue as a duplicate of #81

**Closed by scottyab** 2022-01-18 14:44 UTC
Labels: enhancement
