### ISSUE TITLE
Beacon 2.2.1 crashes when trying to open BeaconActivity

### ISSUE THREAD

**Issue by rgrapes** [helpscout/beacon-android-sdk-sample#132] opened 2020-09-16 01:16 UTC
Thank you for taking the time to submit an issue with all the details shown below. Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

* Beacon version: 2.2.1 (also 2.2.0)
* Android OS version: Android 11 (and 10)
* Device make/model: Emulator Pixel XL API 30 (and Nexus API 29)

**Steps to reproduce**
1. Beacon.Builder().withBeaconId(...).build() seems to run with no errors.
2. BeaconActivity.open(...) causes immediate crash.

This seems related to https://github.com/helpscout/beacon-android-sdk-sample/issues/124 except I'm using Kotlin 1.3.72. I've also tried 1.4.10 with the same results.

**Actual outcome**
An exception
```
2020-09-16 13:06:25.955 6830-6830/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.melonhealth.betame.staging, PID: 6830
    java.lang.NoSuchMethodError: No virtual method elapsedNow()D in class Lkotlin/time/TimeMark; or its super classes (declaration of 'kotlin.time.TimeMark' appears in /data/app/~~VmAZPW2SmQQQqTXG4s2yxw==/com.melonhealth.betame.staging-bHk0gp3ivQxvP0W4mfuudA==/base.apk!classes2.dex)
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:36)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:60)
        at com.helpscout.beacon.a.d.a.c$a$a.a(Unknown Source:17)
```

**Expected outcome**
Shouldn't crash.

**Screenshots or GIFs**
Any examples of the issue

**Comment by aliripe** [comment] 2020-09-16 08:18
Hi @rgrapes,

You can force our SDK to use the latest version of Koin by adding the following piece of code to your root `build.gradle` file:

```
allprojects {
    ...

    ext.koinVersion = '2.2.0-beta-1'

    configurations.all {
        resolutionStrategy {
            force "org.koin:koin-core:$koinVersion"
            force "org.koin:koin-android:$koinVersion"
            force "org.koin:koin-androidx-scope:$koinVersion"
            force "org.koin:koin-androidx-viewmodel:$koinVersion"
        }
    }
}
```

Could you try adding that and see if it fixes the issue? This would unblock you until we push a new version of the SDK with the updated dependency if Koin is indeed the culprit.

Let us know if it works!

**Comment by rgrapes** [comment] 2020-09-18 00:11
Hi,

No luck with that suggestion. A different exception is reported though:
```
2020-09-18 12:09:32.617 10607-10607/com.melonhealth.betame.staging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.melonhealth.betame.staging, PID: 10607
    java.lang.NoSuchMethodError: No virtual method getRootScope()Lorg/koin/core/scope/ScopeDefinition; in class Lorg/koin/core/module/Module; or its super classes (declaration of 'org.koin.core.module.Module' appears in /data/app/~~H8wb8e3LUDUOua2fvHCnjQ==/com.melonhealth.betame.staging-5Fb2jNTPzSMVP2BN8xl24Q==/base.apk!classes2.dex)
        at com.helpscout.beacon.internal.presentation.inject.modules.AppModuleKt$appModule$1.invoke(Unknown Source:9)
        at com.helpscout.beacon.internal.presentation.inject.modules.AppModuleKt$appModule$1.invoke(Unknown Source:2)
        at org.koin.dsl.ModuleKt.module(Module.kt:31)
        at org.koin.dsl.ModuleKt.module$default(Module.kt:29)
        at com.helpscout.beacon.internal.presentation.inject.modules.AppModuleKt.<clinit>(Unknown Source:6)
        at com.helpscout.beacon.internal.presentation.inject.modules.AppModuleKt.getAppModule(Unknown Source:0)
        at com.helpscout.beacon.a.d.a.c$a.<clinit>(Unknown Source:18)
        at com.helpscout.beacon.a.d.a.c.<clinit>(Unknown Source:0)
```

**Comment by sipersso** [comment] 2020-09-18 09:24
I am getting the same thing using 1.3.72. This issue is currently blocking an important update for me. 

@aliripe: I can verify that the workaround provided does not work and I am getting the same error message as @rgrapes.

Any ideas on how to work around this? 

My opinion: I think shipping the HelpScout Beacon using a beta version of Koin (which would fix this) would be a better option than letting the HelpScout beacon crash for those using the library. It can't get worse than a crash when starting the beacon.

**Comment by sipersso** [comment] 2020-09-18 13:11
This is interesting. For me it actually worked in 1.3.72 prior to today. Then for no obvious reason, HelpScout started crashing, even on 1.3.72. I couldn't figure out why. 

After some trial and error, I backtraced the error to when I removed okhttp and retrofit from the app. Interestingly enough, when I added those dependencies back, the app stopped crashing! 

@rgrapes I wouldn't trust this workaround one bit, but I found that all I needed to keep around was this dependency:
` implementation("com.squareup.okhttp3:logging-interceptor:4.8.0")`

If this is included, the app works and HelpScout doesn't crash, if I remove that line, the app crashes when starting the beacon.

**Comment by aliripe** [comment] 2020-09-18 14:59
Hi @sipersso, @rgrapes,

Thank you so much for the investigation and for helping out! We'll keep that in mind when investigating this further. Very interesting findings indeed...

At the same time, we're indeed considering pushing a version of the SDK with the beta version of Koin for the same reasons you mentioned, we'll keep you posted!

**Comment by sipersso** [comment] 2020-09-18 15:02
I would actually be more comfortable shipping a beta version of next HelpScout update than to rely on the current "hack" I am using. Totally understand if you don't wan to ship a release version, but a beta that fixes this issue would be great. 

Thanks for the reply!

**Comment by scottyab** [comment] 2020-09-22 13:57
I'm trying to reproduce this issue. We're not not using OkHttp 4.x due to Retrofit 2 only supporting 3.x. I cannot understand why adding `implementation("com.squareup.okhttp3:logging-interceptor:4.8.0"` resolves this issue? 🤔   

@sipersso you mentioned you "backtraced the error to when I removed okhttp and retrofit from the app" which versions did you remove? 

It would really help if @rgrapes and/or @sipersso you could email us (help@helpscout.com with subject FAO the Mobile Team) your dependancy list/block so we can attempt to reproduce and confirm Koin 2.0.0 beta 1 does indeed fix the error. Thanks

**Comment by sipersso** [comment] 2020-09-22 14:19
@scottyab I don't undertand it either to be honest. I just happened to come across it as the app started crashing after I removed these dependencies for other reasons. But the crash is definitely the same one as listed here and the crash went away when adding the logging-interceptor dependency. 

The logging feature in Koin was deprecated a few versions back (1.5x something?) and completely removed in 1.4 from what I have understood, but I don't understand how this would make a difference here on Kotlin 1.3.72. The Koin threads I have read around this only mentions kotlin 1.4. 

I have sent you a text file containing the output of gradlew app:dependencies. Hope it helps!

**Comment by scottyab** [comment] 2020-09-23 10:45
@rgrapes We think the issue could be related to targeting API 30 and running on Android 11. In Beacon 2.2.2 we will update our Retrofit dependency to use 2.8.2 which crucially includes OKHttp 3.14.9 that has an Android platform detection fix that we think is one of the issues you have seen.

**Comment by aliripe** [comment] 2020-09-24 10:54
Hi there @rgrapes! Beacon 2.2.2 is out! Let us know if you're still running into this issue, I'm going to close this ticket for now, feel free to re-open if it persists!

**Closed by aliripe** 2020-09-24 10:54 UTC
Labels: bug

**Comment by rgrapes** [comment] 2020-09-27 20:36
Beacon 2.2.2 seems to be working well. Thanks for your help
