### ISSUE TITLE
Loose notification with helpscout in app

### ISSUE THREAD

**Issue by ugoconsonni** [helpscout/beacon-android-sdk-sample#177] opened 2021-11-26 20:48 UTC
Hi i use helpscout 2 in react native,
my app use an another service for push notification (wonder push) but when i install helpscout in project, i don't receive notification beacause helpscout use 
```
<service
android:name="com.helpscout.beacon.internal.common.push.fcm.BeaconFirebaseMessagingService"
android:stopWithTask="false" >
<intent-filter>
<action android:name="com.google.firebase.MESSAGING_EVENT" />
</intent-filter>
</service>
```

and wonder push same 
```

<service
android:name="com.wonderpush.sdk.push.fcm.FirebaseMessagingService"
android:exported="false" >
<intent-filter>
<action android:name="com.google.firebase.MESSAGING_EVENT" />
</intent-filter>
</service>
```

do you have any solution ?

**Comment by aliripe** [comment] 2021-11-29 08:33
Hi @ugoconsonni,

He have an entry in our Beacon for Android documentation that explains what to do if your application is already enabled for FCM, you can [check it out here](https://developer.helpscout.com/beacon-2/android/#your-application-is-already-enabled-for-fcm).

In summary, you need to provide your own implementation of `FirebaseMessagingService` and forward the `onNewToken()` and `onMessageReceived()` callbacks to our SDK – and in your case, also to WonderPush. 

I've done some research, and here's [a post in WonderPush](https://discuss.wonderpush.com/t/wonderpush-and-fcm/195/2) that explains how to forward those callbacks to their service.

That should make both services work as intended so I'm going to close this ticket for now. Do not hesitate to open another one if you have any more issues with push notifications or any other parts of the SDK!

**Closed by aliripe** 2021-11-29 08:33 UTC
Labels: question
