### ISSUE TITLE
Close button terminates host app. 

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#131] opened 2020-09-10 10:56 UTC
Beacon version: 2.2.1

Steps to reproduce:
1: Open the beacon straight to the contact form (docs and chat disabled)
2: Send message and close the beacon.
3: Repeat step 1. You will now see a back button (why?)
4: Press back.
5: Press the X button to close

Actual:
Pressing the x button in the last step will not only close the beacon, it will terminate the whole app! 

Expected:
Pressing x should only exit the beacon. Not close the host app. 

See sample video that illustrates the issue. In the video I press the "Return home" button after sending the message, but this is not needed to reproduce the issue. The steps outlined in this issue is enough.

[state_issue.mp4.zip](https://github.com/helpscout/beacon-android-sdk-sample/files/5201129/state_issue.mp4.zip)

**Comment by shaunmcilroy** [comment] 2020-09-10 11:11
Hey @sipersso thanks for reporting this. We've been able to reproduce and have an internal card logged for our team to investigate. We'll be in touch with more updates once we have them [ANDSDK-577](https://helpscout.atlassian.net/browse/ANDSDK-577)

**Comment by scottyab** [comment] 2020-10-05 15:06
Hey @sipersso I've been investigating this a bit deeper today. 

> 3: Repeat step 1. You will now see a back button (why?)

For some context the reason you are seeing the up button here is that after a successful send there are previous conversations/messages so the back/up here takes the user to the Ask chooser where they can access the previous conversations. 

As far as I can tell the Beacon SDK is not terminating your app it's just that when selecting the up icon we're using the `androidx.core.app.TaskStackBuilder` to create a new task stack. This is needed as you're opening directly to the contact page we have to use create the HomeActivity (that houses the Ask chooser) i.e cannot just go back. When pressing the [X] on the home screen in step 5 we're just finishing the HomeActivity and it doesn't go back to the host app as it's in a different task stack. Incidently in my testing the back button has the same effect as [X] here. I'm continuing to investigate just thought I'd share my findings so far.

**Comment by sipersso** [comment] 2020-10-05 15:55
> As far as I can tell the Beacon SDK is not terminating your app it's just that when selecting the up icon we're using the `androidx.core.app.TaskStackBuilder` to create a new task stack. This is needed as you're opening directly to the contact page we have to use create the HomeActivity (that houses the Ask chooser) i.e cannot just go back.

I think you have the solution right there. You shouldn't go back. If the user has not been in the destination, you should open a new activity instead and let Android handle the back navigation. Creating a new TaskStack to rewrite history without using addParentStack to add the host application history won't work right?

**Comment by sipersso** [comment] 2020-10-05 20:04
An idea that just came to mind, when reading this thread: https://github.com/helpscout/beacon-android-sdk-sample/issues/108.

For my use case, it might be an option to keep docs enabled but to open the beacon with the "Ask First" focus mode. It is an extra step for the customer to reach out, but might work if modifying texts slightly. This would avoid the back button issues as I would actually be starting the "Home Activity", and also would avoid the current confusing back button behavior, plus make "previous conversations" less confusing to get to.

**Comment by aliripe** [comment] 2020-11-25 13:56
@sipersso we've pushed a fix for this as part of the new Beacon 2.3.0 release. Please see the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details.

**Closed by aliripe** 2020-11-25 13:56 UTC
Labels: bug
