### ISSUE TITLE
Beacon crashes with IllegalStateException "KoinApplication has not been started"

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#98] opened 2020-06-01 11:25 UTC
I have not been able to reproduce this locally, but I do see it in production. 

* Beacon version: 2.0.2
* Android OS version: 10
* Device make/model: Only on Samsung devices so far (Galaxy Note9,  Galaxy S9+)

I have not been able to reproduce it locally, but the please find the attached stacktraces:

```
Fatal Exception: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{sp.repcount/com.helpscout.beacon.internal.ui.domain.message.BeaconSendMessageActivity}: java.lang.IllegalStateException: KoinApplication has not been started
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3341)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```
```
Caused by java.lang.IllegalStateException: KoinApplication has not been started
       at org.koin.core.context.GlobalContext.get(GlobalContext.java:37)
       at org.koin.core.KoinComponent$DefaultImpls.getKoin(KoinComponent.java:32)
       at com.helpscout.beacon.a.b.a.a$a.a(a.java:15)
       at com.helpscout.beacon.internal.ui.common.c.getKoin(c.java)
       at com.helpscout.beacon.internal.ui.domain.message.BeaconSendMessageActivity.<init>(BeaconSendMessageActivity.java:25)
       at java.lang.Class.newInstance(Class.java)
       at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
       at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
       at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3329)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by jotaemepereira** [comment] 2020-06-02 11:28
Hey @sipersso, thanks for the heads-up on this crash. I've just created a [ticket](https://helpscout.atlassian.net/browse/ANDSDK-444) in our internal tool to track it and discuss it with the team. I will let you know as soon as I get some news. Thanks!

**Comment by jotaemepereira** [comment] 2020-06-03 12:35
Hi @sipersso, is it possible for you to bump Beacon to the latest version? We fixed several bugs since 2.0.2. I know you mentioned you weren't able to reproduce this locally, but if you run into this issue locally, let us know the reproduction steps.

I will leave this issue open so we can track any other user experiencing this crash.

**Comment by sipersso** [comment] 2020-06-03 12:44
I have a few concerns regarding the UI of the 2.1.0 release, which makes me hesitate to upgrade:
https://github.com/helpscout/beacon-android-sdk-sample/issues/95 https://github.com/helpscout/beacon-android-sdk-sample/issues/94 

#95 is probably a bug since it doesn't behave the same on all platforms
#94 is more feedback of the general design, where I disagree with a few choices made

This issue doesn't seem to be super common, so my guess is that it only happens in rare cases, like state restoration.

**Comment by jotaemepereira** [comment] 2020-06-04 22:36
Hey @sipersso! Thanks for the feedback, we appreciate it. We had a discussion with the team, and we decided to close this issue because we are only supporting fixes and improvements in newer versions of the SDK, and we were not able to reproduce it.

About the two issues you mentioned, we currently have them tracked in our internal system, and we will let you know when we have some news about them.

Again, thanks for all the feedback! It is great to have developers involved with the SDK.

**Closed by jotaemepereira** 2020-06-04 22:36 UTC
Labels: bug
